---
- name: Install tools and scanners for CI server
  hosts: all
  become: yes

  tasks:
    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - unzip
        - wget
        - curl
        - gnupg
        - software-properties-common
        - default-jdk
        - jq

    - name: Install SonarQube Scanner CLI
      unarchive:
        src: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip"
        dest: /opt
        remote_src: yes

    - name: Symlink sonar-scanner to /usr/local/bin
      file:
        src: /opt/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner
        dest: /usr/local/bin/sonar-scanner
        state: link
        force: yes

    - name: Download Trivy binary
      get_url:
        url: https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
        dest: /tmp/trivy.deb

    - name: Install Trivy
      apt:
        deb: /tmp/trivy.deb
